version: '3'

services:
    db:
      image: "postgres:11.8-alpine"
      volumes:
        - ./docker/db/init:/docker-entrypoint-initdb.d
        - ./docker/db/data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DEV_DB=auth_api_demo_dev
        - POSTGRES_TEST_DB=auth_api_demo_test
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres