### sign up

POST http://localhost:4000/sign-up
Content-Type: application/json

{
  "user": {
    "email": "foo@example.com",
    "password": "somePassword"
  }
}

### sign in

POST http://localhost:4000/sign-in
Content-Type: application/json

{
  "email": "foo@example.com",
  "password": "somePassword"
}

### whoami

GET http://localhost:4000/whoami
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoX2FwaV9kZW1vIiwiZXhwIjoxNTkyMDU3NjQzLCJpYXQiOjE1ODk2Mzg0NDMsImlzcyI6ImF1dGhfYXBpX2RlbW8iLCJqdGkiOiJlNDE2YWM5YS01NDIxLTQyMmYtOTNkMC0zODNiMGI4YWMyY2QiLCJuYmYiOjE1ODk2Mzg0NDIsInN1YiI6IjExIiwidHlwIjoiYWNjZXNzIn0.WDLzf5tlm41-ASOO-EuaHBNWWlYf-65weYPw5R2Zkd4NcVOCR4dY2D6iGTKe25U9G08IRJGIebpAPPpJx5A2ug